import = [
    "~/.config/alacritty/themes/themes/coolnight.toml"
]

[env]
TERM = "xterm-256color"

[window]

position.x = 200
position.y = 30

padding.x = 0
padding.y = 0

dimensions.columns = 180
dimensions.lines = 55

[font]
normal.family = "Hack Nerd Font"

#regular
size = 11

[scrolling]
history = 10000

[selection]
save_to_clipboard = true

