import = [
    #"~/AppData/Roaming/alacritty/themes/themes/coolnight.toml"
    #"~/AppData/Roaming/alacritty/themes/themes/alabaster.toml"
    "~/AppData/Roaming/alacritty/themes/themes/nordic.toml"
    #"~/AppData/Roaming/alacritty/themes/themes/solarized_dark.toml"
    # "~/AppData/Roaming/alacritty/themes/themes/github_dark_dimmed.toml"
    # "~/AppData/Roaming/alacritty/themes/themes/github_dark_high_contrast.toml"
]
working_directory = "C:\\Users\\alexya"

[env]
TERM = "xterm-256color"

[window]

position.x = 200
position.y = 30

padding.x = 0
padding.y = 0

dimensions.columns = 180
dimensions.lines = 50

[font]
# normal.family = "Inconsolata LGC Nerd Font Mono"
# normal.family = "MesloLGS Nerd Font Mono"
normal.family = "Hack Nerd Font"

#regular
size = 12

[scrolling]
history = 10000

[selection]
save_to_clipboard = true

